### ISSUE TITLE
CocoaPods更新出现问题

### ISSUE THREAD

**Issue by LockeXia** [shaojiankui/JKCountDownButton#7]
CocoaPods could not find compatible versions for pod "JKCountDownButton":
  In snapshot (Podfile.lock):
    JKCountDownButton (= 1.2.0)

  In Podfile:
    JKCountDownButton (~> 1.2.0)

None of your spec sources contain a spec satisfying the dependencies: `JKCountDownButton (~> 1.2.0), JKCountDownButton (= 1.2.0)`.

**Comment by shaojiankui** [comment]
好了没，要不试下1.3.0

**Comment by shaojiankui** [comment]
1.2.0版本被删除了，因为推荐使用1.3.0

**Comment by LockeXia** [comment]
好了
